# Generated by Django 2.2.1 on 2019-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('T', 'trans')], default=None, max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('salary', models.IntegerField()),
                ('bus_no', models.PositiveSmallIntegerField(null=True)),
                ('area', models.CharField(max_length=512, null=True)),
                ('experience', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('T', 'trans')], default=None, max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('salary', models.IntegerField()),
                ('area', models.CharField(choices=[('CW', 'Class Worker'), ('PW', 'Peun Worker'), ('PA', "Principal's Assistant"), ('Te', 'Technecian'), ('SA', 'School Administrator')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('T', 'trans')], default=None, max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=128)),
                ('highest_degree', models.CharField(max_length=128)),
                ('experience', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
