# Generated by Django 2.2.1 on 2019-09-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MIGD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('age', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.TextField(max_length=10)),
                ('query', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedMentoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('age', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.TextField(max_length=10)),
                ('review', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('age', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.TextField(max_length=10)),
            ],
        ),
    ]
