# Generated by Django 2.2.1 on 2019-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='work',
            field=models.TextField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
