# Generated by Django 2.2.1 on 2019-07-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
