# Generated by Django 2.2.1 on 2019-07-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='customer',
        ),
    ]
