# Generated by Django 2.2.1 on 2019-11-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('rating', models.TextField(max_length=100)),
                ('release_date', models.TextField(max_length=100)),
                ('duration', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
