# Generated by Django 2.2.1 on 2019-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilecreate', '0002_auto_20190713_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
