# Generated by Django 2.2.1 on 2019-07-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilecreate', '0003_alumni_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
